export type NewWordType = {
  word: string;
  translate: string;
  createDate?: {
    utcMS: number;
    utcOffsetMS: number;
  };
};

export const fruits_vegetables: NewWordType[] = [
  { word: 'Apple', translate: 'Яблоко' },
  { word: 'Banana', translate: 'Банан' },
  { word: 'Potato', translate: 'Картофель' },
  { word: 'Tomato', translate: 'Томат' },
  { word: 'Carrot', translate: 'Морковь' },
  { word: 'Orange', translate: 'Апельсин' },
  { word: 'Onion', translate: 'Лук' },
  { word: 'Lemon', translate: 'Лимон' },
  { word: 'Cucumber', translate: 'Огурец' },
  { word: 'Garlic', translate: 'Чеснок' },
  { word: 'Strawberry', translate: 'Клубника' },
  { word: 'Grapes', translate: 'Виноград' },
  { word: 'Lettuce', translate: 'Салат-латук' },
  { word: 'Watermelon', translate: 'Арбуз' },
  { word: 'Pepper', translate: 'Перец' },
  { word: 'Pineapple', translate: 'Ананас' },
  { word: 'Broccoli', translate: 'Брокколи' },
  { word: 'Mango', translate: 'Манго' },
  { word: 'Peach', translate: 'Персик' },
  { word: 'Spinach', translate: 'Шпинат' },
  { word: 'Blueberry', translate: 'Черника' },
  { word: 'Zucchini', translate: 'Кабачок' },
  { word: 'Cherry', translate: 'Вишня' },
  { word: 'Pear', translate: 'Груша' },
  { word: 'Cabbage', translate: 'Капуста' },
  { word: 'Avocado', translate: 'Авокадо' },
  { word: 'Melon', translate: 'Дыня' },
  { word: 'Raspberry', translate: 'Малина' },
  { word: 'Pumpkin', translate: 'Тыква' },
  { word: 'Celery', translate: 'Сельдерей' },
  { word: 'Kiwi', translate: 'Киви' },
  { word: 'Eggplant', translate: 'Баклажан' },
  { word: 'Plum', translate: 'Слива' },
  { word: 'Corn', translate: 'Кукуруза' },
  { word: 'Radish', translate: 'Редис' },
  { word: 'Beetroot', translate: 'Свёкла' },
  { word: 'Apricot', translate: 'Абрикос' },
  { word: 'Pomegranate', translate: 'Гранат' },
  { word: 'Fig', translate: 'Инжир' },
  { word: 'Cauliflower', translate: 'Цветная капуста' },
  { word: 'Green beans', translate: 'Зелёная фасоль' },
  { word: 'Ginger', translate: 'Имбирь' },
  { word: 'Lime', translate: 'Лайм' },
  { word: 'Coconut', translate: 'Кокос' },
  { word: 'Brussels sprouts', translate: 'Брюссельская капуста' },
  { word: 'Sweet potato', translate: 'Батат' },
  { word: 'Dates', translate: 'Финики' },
  { word: 'Passion fruit', translate: 'Маракуйя' },
  { word: 'Artichoke', translate: 'Артишок' },
];

export const phrasalVerbs_words: NewWordType[] = [
  { word: 'break into', translate: 'врываться' },
  { word: 'break out', translate: 'сбежать' },
  { word: 'bring down', translate: 'расстроить' },
  { word: 'call off', translate: 'отменять' },
  { word: 'catch up', translate: 'догонять, наверстывать' },
  { word: 'check out', translate: 'проверять, смотреть' },
  { word: 'come across', translate: 'случайно встретить, натолкнуться' },
  { word: 'cut down', translate: 'сокращать, уменьшать' },
  { word: 'get along', translate: 'ладить, уживаться' },
  { word: 'give up', translate: 'сдаваться, бросать' },
  { word: 'look after', translate: 'присматривать' },
  { word: 'make up', translate: 'придумывать, мириться' },
  { word: 'turn up', translate: 'появляться, приходить' },
  { word: 'bring up', translate: 'поднимать (вопрос), воспитывать' },
  { word: 'fill out', translate: 'заполнять (форму)' },
  { word: 'get over', translate: 'преодолеть, оправиться' },
  { word: 'hold on', translate: 'подождать, держаться' },
  { word: 'look forward to', translate: 'ждать с нетерпением' },
  { word: 'pass out', translate: 'терять сознание, раздавать' },
  { word: 'run into', translate: 'встретить случайно' },
  { word: 'set up', translate: 'организовывать, устраивать' },
  { word: 'take off', translate: 'снимать (одежду), взлетать' },
  { word: 'work out', translate: 'решать, тренироваться' },
  { word: 'break up', translate: 'расставаться' },
  { word: 'carry on', translate: 'продолжать' },
  { word: 'drop off', translate: 'завозить, подбросить' },
  { word: 'figure out', translate: 'разобраться, понять' },
  { word: 'give in', translate: 'уступать, сдаваться' },
  { word: 'look up', translate: 'искать информацию' },
  { word: 'pick up', translate: 'забирать, поднимать' },
  { word: 'put off', translate: 'откладывать' },
  { word: 'turn down', translate: 'отказываться, убавлять (звук)' },
  { word: 'turn on', translate: 'включать' },
  { word: 'blow up', translate: 'взорваться, разозлиться' },
  { word: 'come up with', translate: 'придумать, предложить' },
  { word: 'drop by', translate: 'заглянуть, заскочить' },
  { word: 'fill in', translate: 'заполнять (пропуски), заменять' },
  { word: 'hold up', translate: 'задерживать, ограбить' },
  { word: 'run out of', translate: 'заканчиваться (о запасах)' },
  { word: 'show up', translate: 'появляться, приходить' },
  { word: 'back up', translate: 'поддерживать, создавать резервную копию' },
  { word: 'bring about', translate: 'вызывать, приводить к' },
  { word: 'check in', translate: 'регистрироваться (в отеле, аэропорту)' },
  { word: 'come back', translate: 'возвращаться' },
  { word: 'cut out', translate: 'исключать, вырезать' },
  { word: 'get away', translate: 'убежать, уехать, ускользнуть' },
  { word: 'give away', translate: 'раздавать, выдавать (секрет)' },
  { word: 'look out', translate: 'быть осторожным, выглядывать' },
  { word: 'set off', translate: 'отправляться, запускать (сигнал)' },
  { word: 'take over', translate: 'перенимать (контроль, обязанности)' },
];
export const idioms_words: NewWordType[] = [
  { word: 'A piece of cake', translate: 'Проще простого' },
  { word: 'Rain or shine', translate: 'Что бы не произошло' },
  { word: 'Hit the sack', translate: 'Лечь спать' },
  { word: 'Cutting corners', translate: 'Делать кое-как, халтурить' },
  { word: 'Under the weather', translate: 'Плохо себя чувствовать' },
  { word: 'Spill the beans', translate: 'Выдать секрет' },
  { word: 'Break the ice', translate: 'Разрядить обстановку' },
  { word: 'Hit the nail on the head', translate: 'Попасть в точку' },
  { word: 'Bite the bullet', translate: 'Смириться с чем-то неприятным' },
  { word: 'On the ball', translate: 'Быть внимательным, на высоте' },
  { word: 'Throw shade', translate: 'Критиковать, подшучивать (негативно)' },
  { word: 'Pull someone’s leg', translate: 'Подшучивать, дразнить' },
  { word: 'Speak of the devil', translate: 'Лёгок на помине' },
  { word: 'Let the cat out of the bag', translate: 'Раскрыть секрет' },
  { word: 'Kick the bucket', translate: 'Откинуться, умереть (в шуточной форме)' },
  { word: 'Once in a blue moon', translate: 'Крайне редко' },
  { word: 'The ball is in your court', translate: 'Теперь всё зависит от тебя' },
  { word: 'Go the extra mile', translate: 'Сделать больше, чем требуется' },
  { word: 'Cost an arm and a leg', translate: 'Стоить целое состояние' },
  { word: 'Hit the road', translate: 'Отправиться в путь' },
  { word: 'Bend over backwards', translate: 'Очень стараться, из кожи вон лезть' },
  { word: 'Blow off steam', translate: 'Выпустить пар, разрядиться' },
  { word: 'Throw in the towel', translate: 'Сдаться, признать поражение' },
  { word: 'Shoot the breeze', translate: 'Болтать ни о чём' },
];

export const test: NewWordType[] = [
  { word: '1', translate: 'one' },
  { word: '2', translate: 'two' },
  { word: '3', translate: 'free' },
  { word: '4', translate: 'four' },
  { word: '5', translate: 'five' },
  { word: '6', translate: 'six' },
];
